---
secrets:
  -  env: 'MY_SECRET'
     value: "{{ op://Developers/MySecret/SETUP_SECRET/value }}"
     groups: [group1]
  -  env: 'MY_SECRET2'
     value: "{{ op://Developers/MySecret2/SETUP_SECRET/value }}"
     groups: [group2]
